### ISSUE TITLE
Auto coercion

### ISSUE THREAD

**Issue by jeroen** [patperry/r-corpus#1]
Is there some way to make the `text` class auto coerce into character strings? For example:

```r
test <- tempfile()
jsonlite::stream_out(nycflights13::flights, file(test))
flights3 <- corpus::read_ndjson(test)
```

This gives an error for functions that assume a character vector:

```r
dplyr::group_by(flights3, tailnum)
# Error in grouped_df_impl(data, unname(vars), drop) :
#   cannot group column tailnum, of class 'text'
```

**Comment by patperry** [comment]
Probably not, but I'm open to suggestions. In the meantime, `dplyr::group_by(flights3, as.character(tailnum))` works.

**Comment by patperry** [comment]
The more fundamental issue is that `read_ndjson` will treat JSON character string data as `text`, not as `character`. I'm thinking that the client should have more control over this, with the ability to specify that some columns should be `text` and the others should be `character`. A few options I've thought of so far:

1. `strings_as_text = FALSE`, an option to treat all JSON character strings as text. The control level seems too coarse here, and this behavior is probably never what you want.

2. `text_fields = c("text")`, an option that takes a list of field names to treat as `text`; all other character strings get treated as `character`. Default is to treat a field named `text` (if one exists) as `text`.

3. `text_fields = NULL`. All JSON character strings are `character` by default. This hides the `text` data type from the user unless she explicitly opts for it. Specifying `mmap=TRUE` won't have any effect on memory usage unless you also specify `text_fields`.

 I'm leaning towards option 2 right now.

**Comment by patperry** [comment]
The latest commit (e1c0f2ea97edd25f89c560d55c09b44f3c17d289) implements option 2. I'm closing the issue, but if anyone has a better solution, I'd be happy to hear it.
