### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by juliasilge** [patperry/r-corpus#2]
I am having problems installing this package. When I clone the repo and try to install it locally, I get the following error:

```
Installing corpus
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD  \
  INSTALL '/private/var/folders/07/0sps_qnd3qd7fdj3cq9j8pqw0000gn/T/Rtmp5iBAC7/fileb560165dcc71/r-corpus'  \
  --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library' --install-tests 

* installing *source* package ‘corpus’ ...
** libs
clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG   -I/usr/local/include  -Icorpus/src -fPIC  -Wall -g -O2  -c abbreviations.c -o abbreviations.o
abbreviations.c:17:10: fatal error: 'corpus/src/table.h' file not found
#include "corpus/src/table.h"
         ^
1 error generated.
make: *** [abbreviations.o] Error 1
ERROR: compilation failed for package ‘corpus’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/corpus’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/corpus’
Installation failed: Command failed (1)
```

I get the same error when trying to use `devtools::install_github()`. 

Here is some session info, in case it is helpful:

```
Session info ----------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.0 (2017-04-21)
 system   x86_64, darwin15.6.0        
 ui       RStudio (1.0.143)           
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/New_York            
 date     2017-06-06                  
```

**Comment by patperry** [comment]
Yeah, the package uses a git submodule, so the usual methods won't work. Did the instructions at https://github.com/patperry/r-corpus#building-from-source work for you?

**Comment by patperry** [comment]
I'm sure you're not the only one confused by this. I added a note in the "Installing" section at the top of the README.

**Comment by juliasilge** [comment]
AH, I did not see that. Thanks.

**Comment by jeroen** [comment]
FWIW most R packages just put a copy of the sources rather than a submodule so that it works naturally with `devtools::install_github` and what not.

**Comment by patperry** [comment]
@jeroen right, but that would make development more difficult for me; I'd prefer to break `install_github`. For most of the R packages that do this, the underlying C library doesn't change too often.

**Comment by patperry** [comment]
Slightly easier installation method now, described at https://github.com/patperry/r-corpus#installing

```
install.packages("http://ptrckprry.com/dist/corpus_0.6.1.tar.gz", repos = NULL)
```
