### ISSUE TITLE
Vignette to fix demo problem

### ISSUE THREAD

**Issue by conjugateprior** [patperry/r-corpus#4]
The demo doesn't run when readtext and quanteda are already loaded.  

```
> demo("chinese", "corpus")


	demo(chinese)
	---- ~~~~~~~

Type  <Return>	 to start : 

> # Based on Haiyan Wang's demo at https://github.com/ropensci/textworkshop17/tree/master/demos/chineseDemo
> 
> library("httr")

> library("RColorBrewer")

> library("readtext")

> library("stringi")
Error in unloadNamespace(package) : 
  namespace ‘stringi’ is imported by ‘readtext’, ‘stringr’ so cannot be unloaded
Error in library("stringi") : 
  Package ‘stringi’ version 1.1.2 cannot be unloaded
```
Actually these calls seem to be redundant because you always use fully qualified function names. 

But rather than change this, I've attached a mildly rewritten version of the demo as a [vignette plus updated DESCRIPTION](https://github.com/patperry/r-corpus/files/1096425/chinese-vignette.zip) in which the other libraries you use are 'Suggests'.

I'd offer it as a PR but I'm having a little trouble getting the repo to compile (in RStudio).

**Comment by patperry** [comment]
Thanks, this is great!

(See https://github.com/patperry/r-corpus#building-from-source for instructions on building from source; you're not the first to run into this issue...)
